//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityEntities : DbContext,ISecurityDBEntities
    {
        public SecurityEntities()
            : base("name=SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }

        public int proc_SaveUsers(int? Use_Id, string Use_UserName, string Use_Password, string Use_FirstName, string Use_LastName,
           string Use_Phone, string Use_email, string Use_AddressOfStreet, string Use_City, string Use_State, string Use_Zip,
           bool Use_IsActive, DateTime Use_CreateDate, DateTime? Use_VersionDate)
        {
            var Use_IdParameter = Use_Id.HasValue ?
                new ObjectParameter("Use_Id", Use_Id) :
                new ObjectParameter("Use_Id", typeof(int));

            var Use_UserNameParameter = Use_UserName != null ?
                new ObjectParameter("Use_UserName", Use_UserName) :
                new ObjectParameter("Use_UserName", typeof(string));

            var Use_PasswordParameter = Use_Password != null ?
              new ObjectParameter("Use_Password", Use_Password) :
              new ObjectParameter("Use_Password", typeof(string));

            var Use_FirstNameParameter = Use_FirstName != null ?
             new ObjectParameter("Use_FirstName", Use_FirstName) :
             new ObjectParameter("Use_FirstName", typeof(string));

            var Use_LastNameParameter = Use_LastName != null ?
             new ObjectParameter("Use_LastName", Use_LastName) :
             new ObjectParameter("Use_LastName", typeof(string));

            var Use_PhoneParameter = Use_Phone != null ?
            new ObjectParameter("Use_Phone", Use_Phone) :
            new ObjectParameter("Use_Phone", typeof(string));

            var Use_emailParameter = Use_email != null ?
             new ObjectParameter("Use_email", Use_email) :
                new ObjectParameter("Use_email", typeof(string));

            var Use_AddressOfStreetParameter = Use_AddressOfStreet != null ?
             new ObjectParameter("Use_AddressOfStreet", Use_AddressOfStreet) :
           new ObjectParameter("Use_AddressOfStreet", typeof(string));

            var Use_CityParameter = Use_City != null ?
          new ObjectParameter("Use_City", Use_City) :
          new ObjectParameter("Use_City", typeof(string));

            var Use_StateParameter = Use_State != null ?
         new ObjectParameter("Use_State", Use_State) :
         new ObjectParameter("Use_State", typeof(string));

            var Use_ZipParameter = Use_Zip != null ?
            new ObjectParameter("Use_Zip", Use_Zip) :
            new ObjectParameter("Use_Zip", typeof(string));

           var Use_IsActiveParameter = new ObjectParameter("Use_IsActive", Use_IsActive);

            var Use_CreateDateParameter = new ObjectParameter("Use_CreateDate", Use_CreateDate);

            var Use_VersionDateParameter = Use_VersionDate != null ?
                 new ObjectParameter("Use_VersionDate", Use_VersionDate) :
                 new ObjectParameter("Use_VersionDate", typeof(string));



            return ((IObjectContextAdapter)this)
                .ObjectContext.ExecuteFunction("proc_SaveUsers", Use_IdParameter, Use_UserNameParameter, Use_PasswordParameter, Use_FirstNameParameter, Use_LastNameParameter,
             Use_PhoneParameter, Use_emailParameter, Use_AddressOfStreetParameter, Use_CityParameter, Use_StateParameter, Use_ZipParameter,
             Use_IsActiveParameter, Use_CreateDateParameter, Use_VersionDateParameter);



        }
    }
}
