//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Use_Id { get; set; }
        public string Use_UserName { get; set; }
        public string Use_Password { get; set; }
        public string Use_FirstName { get; set; }
        public string Use_LastName { get; set; }
        public string Use_Phone { get; set; }
        public string Use_email { get; set; }
        public string Use_AddressOfStreet { get; set; }
        public string Use_City { get; set; }
        public string Use_State { get; set; }
        public string Use_Zip { get; set; }
        public bool Use_IsActive { get; set; }
        public System.DateTime Use_CreateDate { get; set; }
        public Nullable<System.DateTime> Use_VersionDate { get; set; }
    }
}
